name: build

on:
    push:
        branches:
            - master

jobs:
    build:
        strategy:
          matrix:
            os:
                - ubuntu-latest
                - windows-latest
                - macos-latest
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v1
            
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 5.0.100
                
            - name: Set env
              run: echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
              
            - name: Clean
              run: |
                dotnet clean ./SuperSocket.JTT.sln --configuration Release
                dotnet nuget locals all --clear

            - uses: dotnet/nbgv@master
              id: nbgv
                
            - name: Build
              run: dotnet build ./SuperSocket.JTT.sln -c Release -p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }} -p:AssemblyFileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }} -p:AssemblyInformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}

            - name: Pack
              run: dotnet pack -c Release -p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} /p:NoPackageAnalysis=true

            - name: Push
              run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/supersocket/api/v3/index.json